-d C:\Users\Alessandro\OneDrive\Desktop\Gowin\Gowin_FPGA_CV\CV_acceleration\impl\gwsynthesis\CV_acceleration.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\Alessandro\OneDrive\Desktop\Gowin\Gowin_FPGA_CV\CV_acceleration\src\top.cst
-cfg C:\Users\Alessandro\OneDrive\Desktop\Gowin\Gowin_FPGA_CV\CV_acceleration\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
